### ISSUE TITLE
generator?

### ISSUE THREAD

**Issue by ml242** [kaicataldo/kaicataldodotcom-hugo#1]
Hey Kai,

What are you using to generate your new site? I was just looking at Roots, is there any software you like?

**Comment by kaicataldo** [comment]
Hey Matt! I fairly recently discovered the world of static site generators and am really loving the workflow. This site is built using [Hugo](http://gohugo.io/), which is great, but if I were to do it again I'd probably use [Hexo](http://hexo.io/) (looks pretty similar to Hugo but is built with JS) or [Metalsmith](http://www.metalsmith.io/) (also JS). I just started a new project using Metalsmith and am loving the flexibility it affords. It works very similarly to Gulp and gives you a TON of control over your build - it's basically a tool to mix and match your own static site generator. In fact, the build file for my new project uses both Gulp and Metalsmith to serve, build, and watch my files as I'm working.
